# LibreSSL include path and compiler settings.
if(WIN32)
	# Append LibreSSL paths for the configurations
	SET(CMAKE_CXX_FLAGS_RELEASE			"${CMAKE_CXX_FLAGS_RELEASE}			/I\"${libressldir}/include\"")
	SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO	"${CMAKE_CXX_FLAGS_RELWITHDEBINFO}	/I\"${libressldir}/include\"")
	SET(CMAKE_CXX_FLAGS_DEBUG			"${CMAKE_CXX_FLAGS_DEBUG}			/I\"${libressldir}-debug/include\"")
	SET(CMAKE_CXX_FLAGS_SDKDEBUG		"${CMAKE_CXX_FLAGS_SDKDEBUG}		/I\"${libressldir}-debug/include\"")
else() # linux
	SET(CMAKE_CXX_FLAGS	"${CMAKE_CXX_FLAGS} -I${libressldir}/include")
endif()


# LibreSSL linker settings.
if(WIN32)
	
	SET(LIBRESSL_LINK_FLAGS_RELEASE			"/LIBPATH:\"${libressldir}/lib\"")
	SET(LIBRESSL_LINK_FLAGS_RELWITHDEBINFO	"/LIBPATH:\"${libressldir}/lib\"")
	SET(LIBRESSL_LINK_FLAGS_DEBUG			"/LIBPATH:\"${libressldir}-debug/lib\"")
	SET(LIBRESSL_LINK_FLAGS_SDKDEBUG			"/LIBPATH:\"${libressldir}-debug/lib\"")
	
	SET(CMAKE_EXE_LINKER_FLAGS_RELEASE			"${CMAKE_EXE_LINKER_FLAGS_RELEASE} ${LIBRESSL_LINK_FLAGS_RELEASE}")
	SET(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO	"${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO} ${LIBRESSL_LINK_FLAGS_RELWITHDEBINFO}")
	SET(CMAKE_EXE_LINKER_FLAGS_DEBUG			"${CMAKE_EXE_LINKER_FLAGS_DEBUG} ${LIBRESSL_LINK_FLAGS_DEBUG}")
	SET(CMAKE_EXE_LINKER_FLAGS_SDKDEBUG			"${CMAKE_EXE_LINKER_FLAGS_SDKDEBUG} ${LIBRESSL_LINK_FLAGS_SDKDEBUG}")
	
	SET(CMAKE_MODULE_LINKER_FLAGS_RELEASE			"${CMAKE_MODULE_LINKER_FLAGS_RELEASE} ${LIBRESSL_LINK_FLAGS_RELEASE}")
	SET(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO	"${CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO} ${LIBRESSL_LINK_FLAGS_RELWITHDEBINFO}")
	SET(CMAKE_MODULE_LINKER_FLAGS_DEBUG				"${CMAKE_MODULE_LINKER_FLAGS_DEBUG} ${LIBRESSL_LINK_FLAGS_DEBUG}")
	SET(CMAKE_MODULE_LINKER_FLAGS_SDKDEBUG			"${CMAKE_MODULE_LINKER_FLAGS_SDKDEBUG} ${LIBRESSL_LINK_FLAGS_SDKDEBUG}")

	target_link_libraries(${CURRENT_TARGET} 
		crypto-49
		ssl-52  # ssl and tls libs are needed for using LibreSSL's LibTLS API.
		tls-25
		Bcrypt.lib # Needed for BCryptGenRandom that crypto-xx uses
		)
else()
	target_link_libraries(${CURRENT_TARGET} PRIVATE
		"${libressldir}/lib/libtls.a"
		"${libressldir}/lib/libssl.a"
		"${libressldir}/lib/libcrypto.a")
endif()
